from items import BIG_HEALTH_POTION, BIG_POISON_POTION, HEALTH_POTION, POISON_POTION

FIGHT_LIMIT = 100
DROPS = [HEALTH_POTION, POISON_POTION, HEALTH_POTION, POISON_POTION, HEALTH_POTION, POISON_POTION, BIG_HEALTH_POTION, BIG_POISON_POTION]
GOLD_REWARD = 50
XP_REWARD = 50
SAVE_PATH = 'save.json'